<?php
include "include/header.php";
include "class/Member.php";
include "class/Department.php";

// Create instances
$member = new Member();
$department = new Department();

// Get data from database
$members = $member->getAllMembers();
$departments = $department->getAllDepartments();
?>

<head>
    <link rel="stylesheet" href="css/members.css">      
</head>

<div class="page-header">
    <h2>Member Management</h2>
    <button class="btn-primary" onclick="openMemberModal()">
        <i class="fas fa-plus"></i> Add Member
    </button>
</div>

<!-- REVERTED: Original search bar and dropdown -->
<div class="search-bar">
    <input type="text" id="memberSearch" placeholder="🔍 Search members..." onkeyup="searchMembers()">
    <select id="departmentFilter" onchange="filterMembers()">
        <option value="">All Departments</option>
        <?php foreach($departments as $dept): ?>
            <option value="<?php echo $dept['id']; ?>"><?php echo htmlspecialchars($dept['name']); ?></option>
        <?php endforeach; ?>
    </select>
</div>

<div class="table-container">
    <table class="data-table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Department</th>
                <th>Join Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody id="memberTable">
            <?php if (!empty($members)): ?>
                <?php foreach ($members as $member): ?>
                    <tr data-member-id="<?php echo $member['id']; ?>">
                        <td><?php echo htmlspecialchars($member['first_name'] . ' ' . $member['last_name']); ?></td>
                        <td><?php echo htmlspecialchars($member['email'] ?? 'N/A'); ?></td>
                        <td><?php echo htmlspecialchars($member['phone'] ?? 'N/A'); ?></td>
                        <td>
                            <span class="department-badge"><?php echo htmlspecialchars($member['department_name'] ?? 'No Department'); ?></span>
                        </td>
                        <td><?php echo date('M j, Y', strtotime($member['join_date'] ?? $member['created_at'])); ?></td>
                        <td class="action-buttons">
                            <button class="btn-icon" onclick="editMember(<?php echo $member['id']; ?>)">
                                <i class="fas fa-edit"></i>
                            </button>
                            <button class="btn-icon btn-danger" onclick="deleteMember(<?php echo $member['id']; ?>)">
                                <i class="fas fa-trash"></i>
                            </button>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="6" class="no-data">No members found</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>
    
    <!-- KEEP: Pagination with management.js classes -->
    <div class="pagination" id="pagination">
        <!-- Pagination will be generated by JavaScript -->
    </div>
</div>

<!-- KEEP: Dynamic Member Modal with management.js styling -->
<div id="memberModal" class="modal">
    <div class="modal-content">
        <div class="modal-header">
            <h3 id="modalTitle">Add New Member</h3>
            <span class="close" onclick="closeMemberModal()">&times;</span>
        </div>
        <div class="modal-body">
            <form id="memberForm" onsubmit="return handleMemberSubmit(event)">
                <input type="hidden" id="memberId" name="id">
                <!-- <div class="form-group">
                
                    <input type="hidden" id="unique_id" name="unique_id" required>
                </div> -->
                <div class="form-group">
                    <label>First Name *</label>
                    <input type="text" id="firstName" name="first_name" required>
                </div>
                <div class="form-group">
                    <label>Last Name *</label>
                    <input type="text" id="lastName" name="last_name" required>
                </div>
                <div class="form-group">
                    <label>Email *</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label>Phone</label>
                    <input type="tel" id="phone" name="phone">
                </div>
                <div class="form-group">
                    <label>Password</label>
                    <input type="password" id="password" name="password">
                </div>
                <div class="form-group">
                    <label>Department</label>
                    <select id="department" name="department_id">
                        <option value="">Select Department</option>
                        <?php foreach($departments as $dept): ?>
                            <option value="<?php echo $dept['id']; ?>"><?php echo htmlspecialchars($dept['name']); ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class="form-group">
                    <label>Join Date</label>
                    <input type="date" id="joinDate" name="join_date">
                </div>
                <div class="form-actions">
                    <button type="button" class="btn-secondary" onclick="closeMemberModal()">Cancel</button>
                    <button type="submit" class="btn-primary" id="submitButton">Add Member</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="js/main.js"></script>
<script src="js/members.js"></script>
<?php include "include/footer.php"; ?>