<?php
include "include/header.php";

// Initialize variables
$attendanceData = [];
$weeklyTrend = ['labels' => [], 'values' => []];
$summary = ['total_present' => 0, 'total_absent' => 0, 'total_activities' => 0, 'avg_attendance_rate' => 0];
$topDepartment = ['department' => 'N/A', 'attendance_rate' => 0];
$departments = [];
$activityTypes = [];

// Get filter values from request or set defaults
$startDate = $_GET['start_date'] ?? date('Y-m-01'); // First day of current month
$endDate = $_GET['end_date'] ?? date('Y-m-d');
$department = $_GET['department'] ?? '';
$activityType = $_GET['activity_type'] ?? '';
?>

<head>
    <link rel="stylesheet" href="css/reports.css">      
</head>

<div class="page-header">
    <h2>Attendance Reports</h2>
    <div class="header-actions">
        <button class="btn-secondary" onclick="exportToCSV()">
            <i class="fas fa-download"></i> Export CSV
        </button>
        <button class="btn-primary" onclick="generateReport()">
            <i class="fas fa-chart-bar"></i> Generate Report
        </button>
        <button class="btn-tertiary" onclick="toggleChart()" id="chartToggleBtn">
            <i class="fas fa-chart-line"></i> Show Chart
        </button>
    </div>
</div>

<div class="report-filters">
    <div class="filter-group">
        <label>Date Range:</label>
        <input type="date" id="startDate" value="<?php echo $startDate; ?>">
        <span>to</span>
        <input type="date" id="endDate" value="<?php echo $endDate; ?>">
    </div>
    <div class="filter-group">
        <label>Department:</label>
        <select id="reportDepartment">
            <option value="">All Departments</option>
            <!-- Departments will be populated via JavaScript -->
        </select>
    </div>
    <div class="filter-group">
        <label>Activity Type:</label>
        <select id="activityType">
            <option value="">All Activities</option>
            <!-- Activity types will be populated via JavaScript -->
        </select>
    </div>
    <div class="filter-group">
        <button class="btn-primary" onclick="applyFilters()">
            <i class="fas fa-filter"></i> Apply Filters
        </button>
    </div>
</div>

<div class="report-summary">
    <div class="summary-card">
        <h4>Total Present</h4>
        <h3 id="totalPresent">0</h3>
        <span class="trend positive">+12%</span>
    </div>
    <div class="summary-card">
        <h4>Average Attendance</h4>
        <h3 id="avgAttendance">0%</h3>
        <span class="trend positive">+5%</span>
    </div>
    <div class="summary-card">
        <h4>Top Department</h4>
        <h3 id="topDepartment">N/A</h3>
        <span id="topDepartmentRate">0% attendance</span>
    </div>
</div>

<!-- Chart Container - Modal Overlay -->
<div class="chart-modal-overlay" id="chartModal" style="display: none;">
    <div class="chart-modal">
        <div class="chart-header">
            <h3>Weekly Attendance Trend</h3>
            <button class="btn-close" onclick="toggleChart()">
                <i class="fas fa-times"></i>
            </button>
        </div>
        <canvas id="attendanceChart" height="300"></canvas>
    </div>
</div>

<div class="table-container">
    <h3>Attendance Records</h3>
    <div class="search-container">
        <div class="search-box">
            <i class="fas fa-search"></i>
            <input type="text" id="search-input" placeholder="Search attendance records...">
        </div>
        <div class="results-count">
            Showing <span id="results-count">0</span> of <span id="total-count">0</span> records
        </div>
    </div>
    <table class="data-table">
        <thead>
            <tr>
                <th>Date</th>
                <th>Activity</th>
                <th>Department</th>
                <th>Present</th>
                <th>Absent</th>
                <th>Attendance Rate</th>
            </tr>
        </thead>
        <tbody id="attendanceTableBody">
            <tr>
                <td colspan="6" class="no-data">Loading data...</td>
            </tr>
        </tbody>
    </table>
    
    <!-- Pagination -->
    <div class="pagination" id="pagination">
        <!-- Pagination buttons will be generated by JavaScript -->
    </div>
    <div class="page-info" id="page-info">
        <!-- Page info will be generated by JavaScript -->
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script>
   
</script>

<!-- Include the updated reports.js -->
<script src="js/report/report.js"></script>

<?php include "include/footer.php"; ?>